// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecases/interfaces/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecases/interfaces/interfaces.go -destination=internal/usecases/mocks/checkout.usecases_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRedisImplementation is a mock of RedisImplementation interface.
type MockRedisImplementation struct {
	ctrl     *gomock.Controller
	recorder *MockRedisImplementationMockRecorder
	isgomock struct{}
}

// MockRedisImplementationMockRecorder is the mock recorder for MockRedisImplementation.
type MockRedisImplementationMockRecorder struct {
	mock *MockRedisImplementation
}

// NewMockRedisImplementation creates a new mock instance.
func NewMockRedisImplementation(ctrl *gomock.Controller) *MockRedisImplementation {
	mock := &MockRedisImplementation{ctrl: ctrl}
	mock.recorder = &MockRedisImplementationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisImplementation) EXPECT() *MockRedisImplementationMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRedisImplementation) Get(key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRedisImplementationMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRedisImplementation)(nil).Get), key)
}

// Set mocks base method.
func (m *MockRedisImplementation) Set(key, value string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockRedisImplementationMockRecorder) Set(key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRedisImplementation)(nil).Set), key, value, ttl)
}
