// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecases/payment.usecases.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecases/payment.usecases.go -destination=internal/usecases/mocks/payment_mocks.go  -package=mocks
//

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	events "payment-service/kafka/events/domain"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCache) Get(key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCacheMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCache)(nil).Get), key)
}

// Set mocks base method.
func (m *MockCache) Set(key, value string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheMockRecorder) Set(key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCache)(nil).Set), key, value, ttl)
}

// MockPaymentImplementation is a mock of PaymentImplementation interface.
type MockPaymentImplementation struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentImplementationMockRecorder
	isgomock struct{}
}

// MockPaymentImplementationMockRecorder is the mock recorder for MockPaymentImplementation.
type MockPaymentImplementationMockRecorder struct {
	mock *MockPaymentImplementation
}

// NewMockPaymentImplementation creates a new mock instance.
func NewMockPaymentImplementation(ctrl *gomock.Controller) *MockPaymentImplementation {
	mock := &MockPaymentImplementation{ctrl: ctrl}
	mock.recorder = &MockPaymentImplementationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentImplementation) EXPECT() *MockPaymentImplementationMockRecorder {
	return m.recorder
}

// ValidatePayment mocks base method.
func (m *MockPaymentImplementation) ValidatePayment(params events.OrderCreated, orderId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePayment", params, orderId)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidatePayment indicates an expected call of ValidatePayment.
func (mr *MockPaymentImplementationMockRecorder) ValidatePayment(params, orderId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePayment", reflect.TypeOf((*MockPaymentImplementation)(nil).ValidatePayment), params, orderId)
}
