// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/mysql/interfaces/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/mysql/interfaces/interfaces.go -destination=internal/repository/mocks/checkout.repository_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "order-service/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCheckoutImplementation is a mock of CheckoutImplementation interface.
type MockCheckoutImplementation struct {
	ctrl     *gomock.Controller
	recorder *MockCheckoutImplementationMockRecorder
	isgomock struct{}
}

// MockCheckoutImplementationMockRecorder is the mock recorder for MockCheckoutImplementation.
type MockCheckoutImplementationMockRecorder struct {
	mock *MockCheckoutImplementation
}

// NewMockCheckoutImplementation creates a new mock instance.
func NewMockCheckoutImplementation(ctrl *gomock.Controller) *MockCheckoutImplementation {
	mock := &MockCheckoutImplementation{ctrl: ctrl}
	mock.recorder = &MockCheckoutImplementationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckoutImplementation) EXPECT() *MockCheckoutImplementationMockRecorder {
	return m.recorder
}

// CreateCheckout mocks base method.
func (m *MockCheckoutImplementation) CreateCheckout(checkout *domain.Checkout) (*domain.Checkout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCheckout", checkout)
	ret0, _ := ret[0].(*domain.Checkout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCheckout indicates an expected call of CreateCheckout.
func (mr *MockCheckoutImplementationMockRecorder) CreateCheckout(checkout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCheckout", reflect.TypeOf((*MockCheckoutImplementation)(nil).CreateCheckout), checkout)
}
